import ContactCards from '@/components/ui/contact/ContactCards'
import GoogleMap from '@/components/ui/contact/GoogleMap'
import HeroSection from '@/components/ui/contact/HeroSection'
import QuoteForm from '@/components/ui/home/QuoteForm'
import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
    title: "Contact | Background Checker",
    description: "Generated by create next app",
    metadataBase: new URL("http://localhost:3000/contact"),
};

const page = () => {
    return (
        <>
            <HeroSection />
            <ContactCards />
            <GoogleMap />
            <QuoteForm />
        </>
    )
}

export default page