import ContactCards from '@/components/ui/contact/ContactCards'
import GoogleMap from '@/components/ui/contact/GoogleMap'
import HeroSectionTwo from '@/components/ui/global/HeroSectionTwo'
import QuoteForm from '@/components/ui/home/QuoteForm'
import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
    title: "Contact | Background Checker",
    description: "Generated by create next app",
    metadataBase: new URL("http://localhost:3000/contact"),
};

const page = () => {
    return (
        <>
            <HeroSectionTwo title="Contact" description="Contact us today to discover how our customized background check solutions enhance your hiring process and ensure a safer workplace." heroImg="contactImg.svg" heroBg="contactBG.jpg" />
            <ContactCards />
            <GoogleMap />
            <QuoteForm />
        </>
    )
}

export default page