import type { Metadata } from "next";
import { Poppins, Outfit } from 'next/font/google'
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import Navbar from "@/components/ui/global/Navbar";
import Footer from "@/components/ui/global/Footer";
import NextTopLoader from "nextjs-toploader";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: '--font-Poppins'
})

export const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: '--font-Outfit'
})

export const metadata: Metadata = {
  title: {
    default: "Home | Aria Global",
    template: "%s"
  },
  description: "Generated by create next app",
  metadataBase: new URL("https://aria.global"),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${outfit.variable} antialiased`}
      >
        <NextTopLoader color="#fff" showSpinner={false} />
        <Toaster position="bottom-center" />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
