import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import Navbar from "@/components/ui/global/Navbar";
import Footer from "@/components/ui/global/Footer";
import NextTopLoader from "nextjs-toploader";
import { roboto } from "./fonts";

export const metadata: Metadata = {
  title: {
    default: "Home | Background Checker",
    template: "%s"
  },
  description: "Generated by create next app",
  metadataBase: new URL("https://aria.global"),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <NextTopLoader color="#fff" showSpinner={false} />
        <Toaster position="bottom-center" />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
