name: Deploy Next.js Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

    - name: Deploy frontend with rsync
      run: |
        rsync -az -e "ssh -i ~/.ssh/id_ed25519" .next $SERVER_USER@$SERVER_HOST:/root/coding/projects/backgroundchecker/frontend/.next

    - name: Reload application with pm2
      run: |
        ssh -i ~/.ssh/id_ed25519 $SERVER_USER@$SERVER_HOST "sudo pm2 reload all"
