name: Build and Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build

      - name: Set up SSH key
        run: |
          # Ensure known_hosts file exists and has correct permissions
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

      - name: Deploy frontend with rsync
        run: |
          # Deploy the .next folder to the server
          rsync -az -e "ssh -i ~/.ssh/id_ed25519" .next $SERVER_USER@$SERVER_HOST:/root/coding/projects/backgroundchecker/frontend/.next

      - name: Reload application with pm2
        run: |
          # Reload the application using pm2 on the server
          ssh -i ~/.ssh/id_ed25519 $SERVER_USER@$SERVER_HOST "sudo pm2 reload all"
